### ISSUE TITLE
Roach2Heterodyne.get_measurement_blocks() block length

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#16]
This method doesn't return 4096-sample blocks, like the corresponding methods for other roaches, and instead seems to return a number of samples that depends on the number of tone frequencies. Is it actually returning data corresponding to a certain number of packets?

There's nothing inherently wrong with this, but it's confusing. It would be very helpful to have comments for these methods.

**Comment by gitj** [comment]
The idea is that different designs have different block lengths, so
get_measurement_blocks is an expert function and get_measurement is the
high level interface. But certainly the documentation can be improved.
On May 4, 2016 8:53 PM, "danielflanigan" <notifications@github.com> wrote:

This method doesn't return 4096-sample blocks, like the corresponding
methods for other roaches, and instead seems to return a number of samples
that depends on the number of tone frequencies. Is it actually returning
data corresponding to a certain number of packets?

There's nothing inherently wrong with this, but it's confusing. It would be
very helpful to have comments for these methods.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ColumbiaCMB/kid_readout/issues/16>

**Comment by danielflanigan** [comment]
Fair enough. Usually I just want get_data_seconds, but occasionally it's useful to have an easy way to get a particular number of samples.

**Comment by gitj** [comment]
@danielflanigan 
Just added #17 to address this use case
