### ISSUE TITLE
need some equivalent of resonator_index for SingleSweepStream and relatives

### ISSUE THREAD

**Issue by gitj** [ColumbiaCMB/kid_readout#9]
The result of the current to_dataframe methods don't have any equivalent to resonator_index. We need something like that.
I propose simply adding a 'resonator_index' or 'index' argument to the __init__ method of SingleSweepStream (and SingleSweep, SingleStream for that matter) that simply gets assigned to self.resonator_index or whatever, such that it can be added to the dataframe.
We could potentially add the argument to the to_dataframe method itself, and then change the list comprehension to call to_dataframe(k) for k in range(num_channels) etc.
@danielflanigan what do you think?

**Comment by danielflanigan** [comment]
@gitj As I see it, there are two indices that could be useful. One is the index of a particular slice of data in a measurement of multiple resonators. This is already available in all of the Array classes: measurement_k = streamarray.stream(k). We can and should propagate this index to the dataframe, but it shouldn't be an instantiation attribute of the Single measurements because they won't always have one. Maybe a private attribute that gets put into the dataframe if it exists?

The other index is our name for a particular resonator across data sets. (This doesn't have to be an integer index, it could really be any name.) In general this isn't knowable when the data is taken, so it shouldn't be part of a measurement. We always assign this "by hand" with some assumptions that we can identify resonators at different times, and I think this has to be an argument of to_dataframe().

**Comment by gitj** [comment]
@danielflanigan I agree about the two indicies, but I don't see how it is available: given measurement_k in your example, there is no way to determine the value of k, which is what I'm trying to do. 
I think it makes much more sense to make it an official attribute initialized with __init__ with a default value of None for the case that it doesn't exist for some reason (although I can't see any situation where it wouldn't exist: we never create any Single... measurements directly, always using a method of some Array measurement).

**Comment by danielflanigan** [comment]
Added number parameter to existing Single- classes.
